apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
  name: nginx-alpine
  namespace: demo
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-alpine
status:
  loadBalancer: {}
