apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
  name: nginx-alpine
  namespace: mike 
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-alpine
status:
  loadBalancer: {}
